src/Entity/ImageResource.php
<?php

namespace Geekco\CmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Geekco\CmsBundle\Validator\Constraints as GeekcoAssert;
use Geekco\CmsBundle\Interfaces\ResourceInterface;
use Geekco\CmsBundle\Entity\Resource;

/**
 * @ORM\Entity(repositoryClass="Geekco\CmsBundle\Repository\ImageResourceRepository")
 * @GeekcoAssert\ImageResource
 */
class ImageResource implements ResourceInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @var string
    * @Assert\Length(max=255)
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $name = 'resource_image';

    /**
    * @var string
    *
    * @ORM\Column(type="string", length=255)
    */
    private $image;

    /**
    * @Assert\File(
    * maxSize="20000k",
    * maxSizeMessage="Le fichier excède 20Mo.",
    * mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/svg+xml", "image/gif"},
    * mimeTypesMessage= "formats autorisés: png, jpeg, jpg, svg, gif"
    * )
    */
    private $imageFile;

    /**
    * @var string
    *
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $temporaryFile;

    /**
    * @var \DateTime
    * @ORM\Column(type="datetime", nullable=true)
    */
    private $updatedAt;

    /**
    * @ORM\ManyToOne(targetEntity="Resource", inversedBy="imageResources")
    */
    private $resource;

    /*
     * Get image
     */
    public function getImage()
    {
        return $this->image;
    }

    /*
     * Set image
     */
    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }


    /*
     * Set imageFile
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        $this->updatedAt = new \DateTime('now');
        return $this;
    }

    /*
     * Get imageFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /*
     * Get updatedAt
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /*
     * Set updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /*
     * Get name
     */
    public function getName()
    {
        return $this->name;
    }

    /*
     * Set name
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    public function getValue()
    {
        return $this->getImage();
    }

    public function setResource(Resource $resource = null)
    {
        $this->resource = $resource;

        return $this;
    }

    public function getResource()
    {
        return $this->resource;
    }


    /*
     * Get temporaryFile
     */
    public function getTemporaryFile()
    {
        return $this->temporaryFile;
    }

    /*
     * Set temporaryFile
     */
    public function setTemporaryFile($temporaryFile)
    {
        $this->temporaryFile = $temporaryFile;
        return $this;
    }


    /*
     * Get id
     */
    public function getId()
    {
        return $this->id;
    }
}

src/Entity/Module.php
<?php

namespace Geekco\CmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Geekco\CmsBundle\Validator\Constraints as GeekcoAssert;
use Geekco\CmsBundle\Traits\LabelableEntity;
use Geekco\CmsBundle\Entity\Module;
use Geekco\CmsBundle\Entity\Resource;
use Geekco\CmsBundle\Entity\Page;
use Geekco\CmsBundle\Traits\PositionableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Module
 *
 * @ORM\Table(name="module")
 * @ORM\Entity(repositoryClass="Geekco\CmsBundle\Repository\ModuleRepository")
 * @GeekcoAssert\Module
 * @UniqueEntity({"name", "isBase"}, repositoryMethod="findByUniqueCriteria")
 *
 */
class Module
{
    use PositionableEntity;
    use LabelableEntity;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Assert\Length(max=255)
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="Module", mappedBy="parent", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $children;

    /**
     * @ORM\ManyToOne(targetEntity="Module", inversedBy="children")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $parent;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBase = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $manageable = true;

    /**
     * @ORM\Column(type="boolean")
     */
    private $onlyOne = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasForm = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $areChildrenPositionable = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPositionableInThePage = true;

    /**
     * @ORM\Column(type="boolean")
     */
    private $creatorAble = false;

    /**
     * @var string
     * @Assert\Length(max=255)
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pathThemeRelative;

    /**
     * @ORM\OneToOne(targetEntity="Resource", cascade={"persist", "remove"})
     */
    private $resource;

    /**
     * @ORM\ManyToOne(targetEntity="Page", inversedBy="modules")
     * @Assert\Valid()
     */
    private $page;

    /**
     * @var array
     * @ORM\Column(type="array", nullable=true)
     */
    private $options;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deletable = true;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasCkeditorResource = false;

    public function __toString()
    {
        return ucfirst($this->name);
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /*
     * Get name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /*
     * Set name
     * @return object
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Module
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add child
     *
     * @param \Geekco\CmsBundle\Entity\Module $child
     *
     * @return Module
     */
    public function addChild(Module $child)
    {
        $this->children[] = $child;
        $child->setParent($this);

        return $this;
    }

    /**
     * Remove child
     *
     * @param \Geekco\CmsBundle\Entity\Module $child
     */
    public function removeChild(Module $child)
    {
        $this->children->removeElement($child);
    }

    /**
     * Get children
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Set parent
     *
     * @param \Geekco\CmsBundle\Entity\Module $parent
     *
     * @return Module
     */
    public function setParent(Module $parent = null)
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * Get parent
     *
     * @return \Geekco\CmsBundle\Entity\Module
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Set isBase
     *
     * @param boolean $isBase
     *
     * @return Module
     */
    public function setIsBase($isBase)
    {
        $this->isBase = $isBase;

        return $this;
    }

    /**
     * Get isBase
     *
     * @return boolean
     */
    public function getIsBase()
    {
        return $this->isBase;
    }

    /**
     * Set manageable
     *
     * @param boolean $manageable
     *
     * @return Module
     */
    public function setManageable($manageable)
    {
        $this->manageable = $manageable;

        return $this;
    }

    /**
     * Get manageable
     *
     * @return boolean
     */
    public function getManageable()
    {
        return $this->manageable;
    }


    /**
     * Set onlyOne
     *
     * @param boolean $onlyOne
     *
     * @return Module
     */
    public function setOnlyOne($onlyOne)
    {
        $this->onlyOne = $onlyOne;

        return $this;
    }

    /**
     * Get onlyOne
     *
     * @return boolean
     */
    public function getOnlyOne()
    {
        return $this->onlyOne;
    }

    /*
     * Get hasForm
     */
    public function getHasForm()
    {
        return $this->hasForm;
    }

    /*
     * Set hasForm
     */
    public function setHasForm($hasForm)
    {
        $this->hasForm = $hasForm;
        return $this;
    }

    /*
     * Get areChildrenPositionable
     */
    public function getAreChildrenPositionable()
    {
        return $this->areChildrenPositionable;
    }

    /*
     * Set areChildrenPositionable
     */
    public function setAreChildrenPositionable($areChildrenPositionable)
    {
        $this->areChildrenPositionable = $areChildrenPositionable;
        return $this;
    }

    /*
     * Get creatorAble
     */
    public function getCreatorAble()
    {
        return $this->creatorAble;
    }

    /*
     * Set creatorAble
     */
    public function setCreatorAble($creatorAble)
    {
        $this->creatorAble = $creatorAble;
        return $this;
    }

    /**
     * Set pathThemeRelative
     *
     * @param string $pathThemeRelative
     *
     * @return Module
     */
    public function setPathThemeRelative($pathThemeRelative)
    {
        $this->pathThemeRelative = $pathThemeRelative;

        return $this;
    }

    /**
     * Get pathThemeRelative
     *
     * @return string
     */
    public function getPathThemeRelative()
    {
        return $this->pathThemeRelative;
    }

    /**
     * Set resource
     *
     * @param \Geekco\CmsBundle\Entity\Resource $resource
     *
     * @return Module
     */
    public function setResource(Resource $resource = null)
    {
        $this->resource = $resource;

        return $this;
    }

    /**
     * Get resource
     *
     * @return \Geekco\CmsBundle\Entity\Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Set page
     *
     * @param \Geekco\CmsBundle\Entity\Page $page
     *
     * @return Module
     */
    public function setPage(Page $page = null)
    {
        $this->page = $page;
        if ($page !== null) {
            $page->addModule($this);
        }

        return $this;
    }

    /**
     * Get page
     *
     * @return \Geekco\CmsBundle\Entity\Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /*
     * Get options
     */
    public function getOptions()
    {
        return $this->options;
    }

    /*
     * Set options
     */
    public function setOptions($options)
    {
        $this->options = $options;
        return $this;
    }


    /*
     * Get deletable
     */
    public function getDeletable()
    {
        return $this->deletable;
    }

    /*
     * Set deletable
     */
    public function setDeletable($deletable)
    {
        $this->deletable = $deletable;
        return $this;
    }

    /*
     * Get hasCkeditorResource
     */
    public function getHasCkeditorResource()
    {
        return $this->hasCkeditorResource;
    }

    /*
     * Set hasCkeditorResource
     */
    public function setHasCkeditorResource($hasCkeditorResource)
    {
        $this->hasCkeditorResource = $hasCkeditorResource;
        return $this;
    }

    /*
     * Get isPositionableInThePage
     */
    public function getIsPositionableInThePage()
    {
        return $this->isPositionableInThePage;
    }

    /*
     * Set isPositionableInThePage
     */
    public function setIsPositionableInThePage($isPositionableInThePage)
    {
        $this->isPositionableInThePage = $isPositionableInThePage;
        return $this;
    }
}

src/Form/ModuleType.php
<?php

namespace Geekco\CmsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Geekco\CmsBundle\Form\ResourceType;
use Geekco\CmsBundle\Form\ModuleType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Geekco\CmsBundle\Entity\Module;

class ModuleType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('resource', ResourceType::class, ['label' => false])
            ->add('children', CollectionType::class, [
                'entry_type' => ModuleType::class,
                'allow_delete' => true,
                'allow_add' => true,
                'prototype' => false,
                'delete_empty' => true,
                'by_reference' => false,
                'label' => false,
                'entry_options' => [
                    'label' => false
                ],
                'required' => false,
            ])

            ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Module::class,
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_module';
    }
}

src/Controller/ModuleController.php
<?php

namespace Geekco\CmsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Geekco\CmsBundle\Entity\Module;
use Symfony\Component\HttpFoundation\JsonResponse;
use Geekco\CmsBundle\Form\ModuleType;
use Symfony\Component\HttpFoundation\Request;
use Geekco\CmsBundle\Services\ModuleManager;

/**
 * @Route("/admin/module")
 */
class ModuleController extends Controller
{

    /**
     * @Route("/clone-child")
     * @Method({"POST"})
     */
    public function cloneChildModule(Request $request, ModuleManager $moduleManager)
    {
        if (!$request->isXmlHttpRequest()) {
            throw new NotFoundHttpException();
        }

        $em = $this->getDoctrine()->getManager();
        $module = $em->getRepository(Module::class)->findOneBy([
            'name' => $request->request->get('name'),
            'isBase' => true
        ]);

        $original = $em->getRepository(Module::class)->find($request->request->get('original'));

        if ($module && $original) {
            if (!$module->getChildren()->isEmpty()) {
                $child = $module->getChildren()->first();

                $newChild = $moduleManager->copy($child);
                $moduleManager->resetModule($newChild);

                $em->persist($newChild);

                $original->addChild($newChild);

                $em->flush();

                return new JsonResponse([
                    'success' => true,
                ]);
            }
        }
        return new JsonResponse([
            'success' => false,
        ]);
    }

    /**
     * @Route("/update/{id}", name="geekco_cms_module_update")
     */
    public function update(Module $module, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(ModuleType::class, $module);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $resource = $module->getResource();
                $resource->setUpdatedAt(new \Datetime('now'));

                if (!$module->getChildren()->isEmpty()) {
                    foreach ($module->getChildren() as $childModule) {
                        $childResource = $childModule->getResource();
                        $childResource->setUpdatedAt(new \Datetime('now'));
                    }
                }

                $em->flush();
                $request->getSession()->getFlashBag()->add('success', "Les changements ont été enregistrés.");
                if ($request->isXmlHttpRequest()) {
                    return new JsonResponse([
                        'success' => true
                    ]);
                }
                return $this->redirectToRoute("geekco_cms_module_update", [
                    'id' => $module->getId()
                ]);
            }
        }
        return $this->render('@GeekcoCms/modules/index.html.twig', [
            'form' => $form->createView(),
            'page' => $module->getPage()
        ]);
    }
}

src/Resources/views/modules/form.html.twig
{% import "@GeekcoCms/macros.html.twig" as macros %}

{% form_theme form "@GeekcoCms/form.html.twig" %}
<div class="section form-container">
    {{form_start(form, {'attr': {"id": 'form-update-module'}})}}

    {% set configuration = module.resource is not null ? module.resource.configuration : null %}
    {%include '@GeekcoCms/modules/resource_form.html.twig' with {'configuration' : configuration, 'form': form}%}

    {% if form.children is defined %}
        <div class="children-module-container" data-positionable="{{module.areChildrenPositionable == true ? 'true': 'false'}}">

            {% for current in form.children  %}

                <div class=" section sub-module pl-1 pr-1 mb-2">
                    <br> 
                    {% set configuration = current.vars.value.resource.configuration  %}
                    {%include '@GeekcoCms/modules/resource_form.html.twig' with {'configuration' : configuration, 'form': current } only %}

                    {% do current.setRendered %}
                    <p class="{{loop.index0 is even ? 'right': 'left'}} d-f jc-c ai-c">
                    <a  data-id="{{current.vars.value.id}}" data-url="{{path('geekco_cms_ajax_delete')}}" data-namespace="\Geekco\CmsBundle\Entity\Module" class=" delete-action waves-effect waves-light btn red lighten-1 white-text tooltipped" data-tooltip="Supprimer la section"><i class="material-icons left">delete</i>section</a>
                    </p>
                    <br>
                </div>



            {% endfor %}
            {% if module.creatorAble == true %}
                <br>
                
                <div class="mt-1">
                    <a data-tooltip="ajouter 1 section" class="tooltipped waves-effect waves-light btn light-green accent-2 off-black-text" id="copy-child" data-name="{{form.vars.value.name}}" data-original="{{form.vars.value.id}}"><i class="material-icons left">playlist_add</i>section</a>
                </div>
            {% endif %}

        </div>
    {% endif %}

      <div class="fixed-action-btn">
      <button class="btn-floating btn-large waves-effect waves-light light-green accent-2" type="submit"><i class="black-text text-lighten-1 material-icons">check</i></button>
      </div>

    {{form_end(form)}}
</div>

src/Resources/views/modules/index.html.twig
{% extends "@GeekcoCms/base.html.twig" %}

{% set module = app.request.attributes.get('module') %}

{% block flash %} 
{% endblock %}

{% block body %}
    {% set page = module.page  %}


    {% if page is not null %}
        <nav class="breadcrumb-nav">
            <div class="nav-wrapper">
                <div class="col s12">
                    <a href="{{path('geekco_cms_page_list')}}" class="breadcrumb">Liste des pages</a>
                    <a href="{{path('geekco_cms_page_update', {'id': page.id})}}" class="breadcrumb">Page {{page.name|capitalize}}</a>
                    <a href="#!" class="breadcrumb hide-on-small-only">Module {{module.label}}</a>
                </div>
            </div>
        </nav>

    {% endif %}

    {{include("@GeekcoCms/flash.html.twig")}}

    <div class="container" id="update_module">
        <div class="row">

            <div class="col s12">

                <h1>{{module.label|capitalize}}</h1>
                {% if module.description is not null %}
                    <p class="card-panel "><i class="material-icons">info</i> {{module.description}}</p>
                {% endif%}

                {% include ('@GeekcoCms/modules/form.html.twig') with {'module': module}%}
            </div>
        </div>
    </div>

{% endblock %}

src/Resources/views/modules/resource_form.html.twig
{% import "@GeekcoCms/macros.html.twig" as macros %}

{% form_theme form "@GeekcoCms/form.html.twig" %}
{% if form.resource.stringResources is defined %}
    {% for f in form.resource.stringResources  %}
        <div class="input-field">
            {{form_row(f)}}
        </div>
    {% endfor %}
{% endif %}

{% if form.resource.textResources is defined %}
    {% for f in form.resource.textResources  %}
        <div class=""> 
            {{form_row(f)}}
        </div>
    {% endfor %}
    <br>
    
{% endif %}

{% if form.resource.pageResources is defined %}
    {% for f in form.resource.pageResources  %}
        <div class="input-field"> 
            {{form_row(f)}}
        </div>
    {% endfor %}
    <br>
    
{% endif %}

{% if form.resource.colorResources is defined %}
    {% for f in form.resource.colorResources  %}
        <div class="input-field"> 
            {{form_row(f)}}
        </div>
    {% endfor %}
    <br>
    
{% endif %}

{% if form.resource.imageResources is defined %}
    {% if configuration['imageResources']['add'] == true %}
        {% set prototype = form_row(form.resource.imageResources.vars.prototype)%}
    {% else %}
        {% set prototype = null %}
    {% endif %}
    <div class="collection-container" id="collection-container-{{form.vars.id}}" data-collection-deletable={{configuration['imageResources']['delete'] == false ? 'false': 'true'}} data-max="1" data-prototype='{{prototype}}' data-add-label="image">
        {% for f in form.resource.imageResources  %}
            {% if loop.index0 is even %}
                <div class='item-collection grey lighten-3 p-1' id="{{f.vars.id}}">
            {% else %}
                <div class='item-collection p-1' id="{{f.vars.id}}">
            {% endif %}
            {{form_row(f)}}

            {% if f.vars.value.image is not null %}
                <img src="{{asset("cms/uploads/" ~ f.vars.value.image)}}" alt="" >
            {% endif %}

                </div>
        {% endfor %}
        {% if configuration['imageResources']['add'] == true %}
            {{macros.add_collection_button("image")}}
        {% endif %}
                </div>
{% endif %}

{% if form.resource.booleanResources is defined %}
    {% for f in form.resource.booleanResources  %}
        <p>
        {{form_row(f)}}
        </p>
    {% endfor %}
{% endif %}

{% if form.resource.integerResources is defined %}
    {% for f in form.resource.integerResources %}
        <div class="input-field">
            {{form_row(f)}}
        </div>
    {% endfor %}
{% endif %}